let
    Source = Excel.Workbook(Web.Contents(#"Tenant Domain" & "Orders.xlsx"), null, true),
    TaskPOIDs_Table = Source{[Item="TaskPOIDs",Kind="Table"]}[Data],
    #"Changed Type1" = Table.TransformColumnTypes(TaskPOIDs_Table,{{"Project Header", type text}, {"Delivered", type text}, {"Picked", type text}, {"Have/Need Asset", type text}, {"SAP#", type text}, {"PO#", type text}, {"RC#", type text}, {"SCHOOL", type text}, {"Task", type text}, {"Status", type text}, {"Issues", type text}, {"PO Deadline", type date}, {"Ready Date", type date}, {"Deliver Date", type date}, {"User Type", type text}, {"Machine Type", type text}, {"Model", type text}, {"Qty", Int64.Type}, {"Cart division", type text}, {"Program", type text}, {"POID", type text}, {"Notes", type text}, {"Pages Printed", type text}, {"Sheet Made", type text}}),
    #"Uppercased Text" = Table.TransformColumns(#"Changed Type1",{{"POID", Text.Upper, type text}}),
    #"Added Custom" = Table.AddColumn(#"Uppercased Text", "DCPS PO#", each Text.Start([#"PO#"],10)),
    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom",{{"DCPS PO#", Int64.Type}}),
    #"Replaced Errors" = Table.ReplaceErrorValues(#"Changed Type2", {{"DCPS PO#", 0}}),
    #"Inserted First Characters" = Table.AddColumn(#"Replaced Errors", "PO_Year", each Text.Start(Text.From([#"DCPS PO#"], "en-US"), 4), type text),
    #"Removed Duplicates" = Table.Distinct(#"Inserted First Characters", {"POID"}),
    #"Added Conditional Column" = Table.AddColumn(#"Removed Duplicates", "Note", each if [Use Note] = "2" then [Notes] else if [Use Note] = "1" then [Issues] else null),
    #"Filtered Rows" = Table.SelectRows(#"Added Conditional Column", each ([POID] <> null ))
in
    #"Filtered Rows"
