let
    Source = Excel.Workbook(Web.Contents(#"Tenant Domain" & "TV%20Sheet.xlsx"), null, true),
    #"Data Entry_Sheet" = Source{[Item="Data Entry",Kind="Sheet"]}[Data],
    #"Changed Type" = Table.TransformColumnTypes(#"Data Entry_Sheet",{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type any}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type any}, {"Column9", type any}, {"Column10", type text}, {"Column11", type any}, {"Column12", type any}, {"Column13", type any}, {"Column14", type any}, {"Column15", type any}, {"Column16", type any}, {"Column17", type number}}),
    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column9", "Column10", "Column11", "Column12", "Column13", "Column14", "Column15", "Column16", "Column17"}),
    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Columns", [PromoteAllScalars=true]),
    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Initials", type text}, {"Action", type text}, {"POID", type text}, {"Quantity", Int64.Type}, {"Image", type text}, {"Type", type text}, {"Location", type text}, {"Date", type datetime}}),
    #"Removed Blank Rows" = Table.SelectRows(#"Changed Type1", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
    #"Uppercased Text" = Table.TransformColumns(#"Removed Blank Rows",{{"POID", Text.Upper, type text}}),
    #"Inserted Date" = Table.AddColumn(#"Uppercased Text", "Date.1", each DateTime.Date([Date]), type date),
    #"Renamed Columns" = Table.RenameColumns(#"Inserted Date",{{"Date", "Time"}, {"Date.1", "Date no time"}}),
    #"Added RCID column" = Table.AddColumn(#"Renamed Columns", "RCID", each Text.Start(Text.AfterDelimiter([POID],"."),4),type text),
    #"Merged Queries" = Table.NestedJoin(#"Added RCID column", {"RCID"}, RCID, {"RCID"}, "RCID.1", JoinKind.LeftOuter),
    #"Expanded RC#" = Table.ExpandTableColumn(#"Merged Queries", "RCID.1", {"RC#"}, {"RC#"}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Expanded RC#",{{"RC#", type text}}),
    #"Removed RCID column" = Table.RemoveColumns(#"Changed Type2",{"RCID"}),
    #"Added School Name column" = Table.AddColumn(#"Removed RCID column", "School Name", each [#"RC#"]&" - "&[Location]),
    #"Added Delivery Qty column" = Table.AddColumn(#"Added School Name column", "Delivery Qty", each Text.AfterDelimiter(Text.AfterDelimiter(Text.AfterDelimiter([POID],"."),"."),".")),
    #"Merged Queries1" = Table.NestedJoin(#"Added Delivery Qty column", {"POID"}, Orders, {"POID"}, "Orders", JoinKind.LeftOuter),
    #"Expanded Ready By Date" = Table.ExpandTableColumn(#"Merged Queries1", "Orders", {"Ready Date"}, {"Ready By Date"}),
    #"Replaced Value" = Table.ReplaceValue(#"Expanded Ready By Date",null,#date(1899, 12, 31),Replacer.ReplaceValue,{"Ready By Date"}),
    #"Added PO# column" = Table.AddColumn(#"Replaced Value", "PO#", each Text.BeforeDelimiter([POID],".")),
    #"Filtered Rows" = Table.SelectRows(#"Added PO# column", each ([POID] <> null))
in
    #"Filtered Rows"
