let
    Source = Excel.Workbook(Web.Contents(#"Tenant Domain" & "TV%20Sheet.xlsx"), null, true),
    LogTable_Table = Source{[Item="LogTable",Kind="Table"]}[Data],
    #"Changed Type1" = Table.TransformColumnTypes(LogTable_Table,{{"Initials", type text}, {"Action", type text}, {"POID", type text}, {"Quantity", Int64.Type}, {"Image", type text}, {"Type", type text}, {"Location", type text}, {"Time", type datetime}, {"Date no time", type date}, {"RC#", type text}, {"School Name", type text}, {"Delivery Qty", Int64.Type}, {"Ready By Date", type date}, {"PO#", type text}}),
    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type1",{"Initials", "Action", "POID", "Quantity", "Image", "Type", "Location", "Time", "Date no time", "RC#", "School Name", "Delivery Qty", "Ready By Date", "PO#"}),
    #"Removed Blank Rows" = Table.SelectRows(#"Removed Other Columns", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
    #"Appended Query" = Table.Combine({#"Removed Blank Rows", #"Data Entry", #"Archive Log"}),
    #"Uppercased Text" = Table.TransformColumns(#"Appended Query",{{"POID", Text.Upper, type text}}),
    #"Capitalized Each Word" = Table.TransformColumns(#"Uppercased Text",{{"Action", Text.Proper, type text}}),
    #"Replaced Value" = Table.ReplaceValue(#"Capitalized Each Word","Qc","QC",Replacer.ReplaceText,{"Action"}),
    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",#date(1899, 12, 31),#date(2021, 1, 1),Replacer.ReplaceValue,{"Ready By Date", "Date no time"}),
    #"Filtered Rows" = Table.SelectRows(#"Replaced Value1", each true),
    #"Merged Queries" = Table.NestedJoin(#"Filtered Rows", {"Action"}, Statuses, {"Statuses"}, "Statuses", JoinKind.LeftOuter),
    #"Expanded Statuses" = Table.ExpandTableColumn(#"Merged Queries", "Statuses", {"Index"}, {"Statuses.Index"}),
    #"Inserted Time" = Table.AddColumn(#"Expanded Statuses", "Time.1", each DateTime.Time([Time]), type time),
    #"Renamed Columns" = Table.RenameColumns(#"Inserted Time",{{"Time.1", "Time Only"}}),
    #"Added Conditional Column" = Table.AddColumn(#"Renamed Columns", "IsAfter4pm", each if [Time Only] > #time(16, 15, 0) then "After 4pm" else "Before 4pm"),
    #"Added Conditional Column2" = Table.AddColumn(#"Added Conditional Column", "IsAfter1:30pm", each if [Time Only] > #time(13, 45, 0) then "After 1:30pm" else "Before 1:30pm"),
    #"Merged Queries1" = Table.NestedJoin(#"Added Conditional Column2", {"POID"}, Orders, {"POID"}, "Orders", JoinKind.LeftOuter),
    #"Expanded Orders" = Table.ExpandTableColumn(#"Merged Queries1", "Orders", {"Program"}, {"Program"})
in
    #"Expanded Orders"
